<h1 id="what-are-neocities">What are Neocities</h1>
<p>For the past couple of days, I have been sifting through the internet&#39;s oldest tradition, neocities. Essentially, neocities is just a bunch of retro, internet personal websites that people make to talk about themselves, share gifs, show art, blog, connect with others, and honestly anything imaginable. Most of the time these sites are completely static and I usually find sites through <a href="https://neocities.org/">neocities.org</a>. Neocities the site offers static hosting for free (while the site stays under 1GB of storage). This is great because I can host my site on neocities at <a href="https://eggbert.neocities.org">eggbert.neocities.org</a> for completely free. This is great and feels similar to GitHub pages and they also offer <a href="https://neocities.org/tutorials">tutorials</a> for things like HTML, CSS, and JavaScript that could prove useful to anyone interested in building their little corner of the internet.</p>
<h2 id="social-aspect">Social aspect</h2>
<p>Some get incredibly creative with the sites, but what sticks out to me is the robust social systems these completely independent sites have. There are so many methods of contacting others and I&#39;ll just leave a short synopsis of those here because it&#39;s honestly very impressive. These are completely independent minds that have all more or less agreed-upon methods of linking pages and having a social network within their neocities.</p>
<ol>
<li><strong>Regular old links</strong>: The obvious one. Just a link to another page. Littered all across these neocities.</li>
<li><strong>88x31 buttons</strong>: These are probably the most creative in my opinion. Essentially if you wanted to, you would create a little 88 x 31 pixel gif with some animated art that would link back to your website and leave it on your website for people to take. What that means is that people who like your site will take your button and put it on their own so that users on their website can click your button to go to your site. It&#39;s fascinating to see how many buttons people create, the lengths they go to in designing them, and especially how many buttons one will host on their site. Some have easily over 50 links to their friends or sites they enjoy visiting and I think this off-the-grid homebrewed way of almost having a followers list is creative.</li>
<li><strong>Chat rooms</strong>: Chat rooms are also another pretty self-explanatory one. You can join a chat room and often pick a name and profile picture. These are a little more foreign to me as far as getting them on the site and how third-party companies fit into the mix.</li>
<li><strong>Guest books</strong>: This one I also found very creative. Many sites have what they call a &quot;guest book&quot; and it&#39;s exactly what it would be in real life. If you visit the website and so please, you can write a message into the guestbook and leave a little mark of yourself. These often let people link to their personal sites and give them the freedom to write whatever they want. These come across as an almost comment-section equivalent but have much less toxic communities (as far as I can tell).</li>
<li><strong>Webrings</strong>: These are also very interesting but also don&#39;t come off as very &quot;personal&quot;. A webring is almost like joining a group of people who have some commonality between themselves that will &quot;join&quot; a webring. Some webring managers require forms to be filled out or applications to be made, but essentially if you are part of a webring, you declare so on your site and probably include some little bit of HTML into your site that will be the actual webring. That bit of HTML will let anyone on your site access the sites of other people in the same webring as you. This can be great for small friend groups or even larger organizations, but with the larger webrings, the sense of community disappears, as it&#39;s just a huge list of names that don&#39;t have any organization or relation.</li>
</ol>
<h2 id="final-thoughts">Final thoughts</h2>
<p>Although I am hosting my site through the <a href="https://neocities.org">neocities</a> service, I was never on the internet for this era of what neocities are trying to emulate so I can&#39;t relate to this style of web design, social interaction, and hobbying. I think the little communities that people form are fun to poke around in and I like the whole &quot;independent from big tech&quot; stance, but the style just isn&#39;t for me. The very pixelated, raw, and chaotic vibes of these neocities collide completely with my appeal for simple and minimal design. Also, there is just so much culture I don&#39;t understand or relate to so that&#39;s why I think it would be really cool if there was a more abstract way of socializing through personal websites on the internet.</p>
<p>What I really mean is this (and this may already exist), but a common way for more modern personal websites, personal blogging, and tech enthusiasts to find each other&#39;s websites in a way like neocities offers. Number one, there&#39;s the dense web of links, guest books, 88 x 31, and webrings that are present in neocities, but the content often isn&#39;t of interest to me. Number two, the neocities website offers a great catalog of the sites that they host so it&#39;s an easy-to-reach central hub that will hold a bunch of neocities, making it really easy to find one and start exploring. Other, non-neocity, personal websites have links and webrings, but the really tough part is first finding one. That&#39;s where number two comes in, and I think a place where people could index and catalog a bunch of personal websites would be a great idea and get many more people excited about becoming their internet nomads.</p>
