<h1 id="hello-is-anyone-there-">Hello? Is Anyone There?</h1>
<p>YES YES, I am still here. Fear not. I&#39;ve simply been a little too scattered to put together a &quot;cohesive&quot; post, but I figured &quot;Eh, I don't care.&quot; Also, I missed writting a little bit, <strong><em>but only a little</em></strong>. My last post was on Advent of Code, which I had a <em>LOT</em> of fun doing, and I&#39;m very thankful to everyone who participated with me, especially <a href="https://onocu.com">_Orange</a>! Since that, I had a relxing break, and was thankful I got to spend time seeing family.</p>
<h2 id="beepboop-nvim">BeepBoop.nvim</h2>
<p>One project I did work on, and eventually got to a semi-polished working state (shocker), was <a href="https://github.com/EggbertFluffle/beepboop.nvim">beepboop.nvim</a>. I was originally planning to make an entire post just about that, but I kinda didn&#39;t do it. Essentially, it is a pretty simple Neovim plugin that makes it easy to incorporate audio cues into neovim. I do this for fun, but I can see this being useful for accecibility reasons or notifications, there are a lot of options. I have a demo and (hopefully) everything one would need to get beepboop.nvim up and running in their Neovim config on the <a href="https://github.com/EggbertFluffle/beepboop.nvim">GitHub repo</a>. I use it all the time, and am open to suggestions while the code is also completely open source, although I have never run an open source project and could really use a real reason to dig into git. Despite that, I&#39;m pretty proud of the state of beepboop.nvim and I received a lot of good feedback on Reddit when I made a post showing it to to <a href="https://www.reddit.com/r/neovim/comments/1hqtyg5/make_neovim_noisy_with_beepboopnvim/">r/neovim</a>.</p>
<h2 id="olivia">Olivia</h2>
<p>Additionally, while I was home, my dad finally caved and let us get a cat. Now we are the proud owners of Olivia, a beautiful tuxedo cat that we adopted from the <a href="https://cliftonanimalshelter.com/">Clifton Animal Shelter</a>. She initially did <em>everything</em> in my room for about a week, but then we got her used to the rest of the house. It&#39;s always nice hearing her playing with some random toy at 2AM or sleeping wherever she pleases during the entire day. Of course I need to leave some pictures so enjoy!</p>
<div>
<img src="../images/olivia_trex.jpg" alt="Olivia T-Rex">
<img src="../images/olivia_woah.jpg" alt="Olivia Woah">
<img src="../images/olivia_eepington.jpg" alt="Olivia Sleeping">
<img src="../images/olivia_tupperware.jpg" alt="Olivia Being Tupperwear">
</div>
<h2 id="new-year-s-resolutions-">New Year&#39;s Resolutions</h2>
<p>I have none!</p>
<h2 id="things-i-want-to-do-in-2025">Things I want to do in 2025</h2>
<p>I hope this is somehow different than New Year&#39;s resolutions, but there are some things I&#39;d like to do this year at some point. Some things I have already made pretty good headway on. One of which was learning a bit about assembly language. To do this, I decided upon the <a href="https://flatassembler.net/">flat assembler</a> or fasm. It was really just the first one that I heard about, and would allow me to just start writing as soon as possible, even though eventually the boilerplate for the gnu assembler will be helpful to learn. I figured some things out and have a couple smaller projects to familiarize myself with how data is moved around, system calls are used, and how functions are generally executed. One of the cooler pet projects I made was a small working shell! I don&#39;t have it hosted remotely, but if anyone wants access to it, just shoot me an email!</p>
<p>The big ticket item though is the chat app I want to put together. I&#39;ve gotten into messaging recently, and looked into services like matrix and irc, from which the latter stuck as something I use semi-regularly! It&#39;s actually a lot of fun too. I&#39;ve figured out znc as a bouncer and how to use weechat as my client. I&#39;m only on libera right now, but the communities they have there are so knoledgable, I don&#39;t see myself needing much more than what they have already. As you can probably see where this is going, I want to build my own chat app, but in assembly, and no C library. I think (hope) it will be a good learning oppourtunity, interfacing with the unix socket api through system calls. </p>
<p>I have already started progress... kinda. I figured since I&#39;ve never used the socket api before, it would be beneficial for me to build a chat app where I have access to the C library and all the functions that make the general process a little easier, so I did it in C. This also let me figure out the general order of operations for a server that is connecting with multiple clients and interfacing between all of them at once. Irc was again a super useful resource for this but somone on #c reccommended <a href="https://beej.us/guide/bgnet/">Beej&#39;s Guide to Network Programming</a>. Beej did a fantastic job at making network programming approachable, and make sense to read about. One thing I&#39;ve learned to love is when teachers remind you that they are human too, by having an interesting personality or showing a general enthusiasm for the topic they are lecturing on. Beej does this by being corny or making a funny analogy, but it really makes the material easier to digest. So with all these amazing resources, I finally put together the chat app in C, which can be found on my GitHub <a href="https://github.com/EggbertFluffle/c_chat_app">here</a>.</p>
<p>This is about where I am now, and I need to figure out how to do some of the basics in assembly without the C library like managing structs, arrays, integer parsing, reversing the order of bytes, et cetera. I will probably post about the assembly chat app when it&#39;s finished but it&#39;s taking a quick hiatus while I have some other big ticket items on my list.</p>
<h2 id="new-keeb">New Keeb</h2>
<p>Not really much to say here. Had been wanting a new keyboard for a while now and finally decided to stop being to frugal and do some good research. I originally wanted a standard kit that just looked nice, but I eventually thought &quot;I&#39;ll probably be typing until I get my government issued neuralink&quot;, so I opted for a <strong>split keyboard</strong>. It is the <a href="https://keeb.io/products/iris-keyboard-split-ergonomic-keyboard">Iris PE</a> with the Cherry MX Browns from my old keyboard. Also with a nice new keycap set, courteous of a good ol&#39; secret santa.</p>
<div>
<img src="../images/my_beloved_keyboard.jpg" alt="Beutifully immaculate split keybaord">
</div>
<h2 id="-it-s-the-little-things-">&quot;It&#39;s the Little Things&quot;</h2>
<p>There&#39;s also a ton of very little things that are always fun to mention. I&#39;ve started C term (3rd quarter) as a student at WPI and I&#39;ve been taking System&#39;s Programming and Discrete Mathematics. System&#39;s is fine, but I&#39;m already pretty familliar with the material. Discrete Mathematics however, is one of the most interesting classes I&#39;ve taken here. It&#39;s completely foreign to any &quot;math&quot; I&#39;ve done before, but everything lines up nicely and it makes me approach problems far differently than before, which I always love. I&#39;ve also always wanted to collect two books just because of how much I hear about them in the computing scene, but now I only want to collect one. I just got my hand on <a href="https://en.wikipedia.org/wiki/Design_Patterns">Design Patterns: Elements of Reusable Object-Oriented Software</a> for only $2.00! Such a steal, and I will absolutely be chipping away at it throughout the year. Besides all that nonsense, myself and some friends are plotting to participate in the <a href="https://itch.io/jam/brackeys-13">Brackey&#39;s Game Jam</a> this Saturday, and I&#39;ve been thinking about making a devlog about it and posting it on YouTube, but that does seem like a lot of work concerning recording and editing, which I don&#39;t know how to do. I&#39;m really excited because we have a musician, an artist and two programmers, so I&#39;m hoping we can pump out something really cool! Until next time, who needs outros for blogs?</p>

<style>
	div {
		display: flex;
		flex-direction: column;
		align-items: center;
	}

	img {
		max-width: 75%;
		margin: 0.5rem;
	}
</style>
